name: Manual Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select Branch to Deploy"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - ui-features

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Selected Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: |
          if [ "${{ inputs.branch }}" == "ui-features" ]; then
            npm run build
            mv build ui-features
          else
            npm run build
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ inputs.branch == 'ui-features' && 'ui-features' || 'build' }}
          clean: true
